# Generated by Django 5.1.3 on 2024-11-24 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleTransportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('vehicle_type', models.CharField(choices=[('small_car', 'Small Car'), ('big_car', 'Big Car'), ('suv', 'SUV'), ('bus', 'Bus')], default='small_car', max_length=10)),
                ('pickup_country', models.CharField(max_length=100)),
                ('pickup_city', models.CharField(max_length=100)),
                ('transport_date', models.DateField()),
                ('status', models.CharField(choices=[('waiting_for_response', 'Waiting for Response'), ('accepted', 'Accepted')], default='waiting_for_response', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
