# Generated by Django 5.1.3 on 2024-11-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_remove_vehicletransportrequest_transport_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicletransportrequest',
            name='delivery_city',
            field=models.CharField(default='Sofia', max_length=100),
        ),
        migrations.AddField(
            model_name='vehicletransportrequest',
            name='delivery_country',
            field=models.CharField(default='Bulgaria', max_length=100),
        ),
    ]
