# Generated by Django 5.1.3 on 2024-12-28 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_vehicletransportrequest_delivery_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicletransportrequest',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'Pending Approval'), ('approved', 'Approved')], default='pending_approval', max_length=20),
        ),
    ]
